### ISSUE TITLE
How to change the output length of mfcc features

### ISSUE THREAD

**Issue by htZhang25** [skaws2003/pytorch-mfcc#1]
Hello,I'm glad to study from your great work,and now I have a question that if I want to implement  the same effect as the following operation which is the mfcc_spec function coming from the sonopy module, how should I set the parameters exactly in your __init__() of class MFCC ?  
namely (self,samplerate=16000,winlen=0.025,winstep=0.01,numcep=13,nfilt=26,nfft=None,lowfreq=0,highfreq=None,preemph=0.97,ceplifter=22,appendEnergy=True):
The operation that I want to implement:
   mfccs = mfcc_spec(
                audio, self.sr=16000, window_stride=(160, 80),
                fft_size=512, num_filt=20, num_coeffs=13
            )
https://github.com/MycroftAI/sonopy/blob/master/sonopy.py This is the link for sonopy.py

**Comment by skaws2003** [comment]
Hello,

I don't know about sonopy, but it seems like the parameters should be like:
sampletate=16000 (sr on sonopy)
winstep= 0.01 (which is 160/16000)
winlen= 0.005 (which is 80/16000)
numcep= 13 (num_coeffs on sonopy)
nfft= 512 (fft_size on sonopy)
nfilt=20 (fft_size on sonopy)

**Comment by htZhang25** [comment]
Thank you for replying me so quickly.I just ignore nfft=512 which confused me about how to use 512.I'll check how it works after this set of setting.Is the feature result supposed to be the same with that with sonopy as to the same audio?you think? Or ,I needn't require the same as long as it is one correct feature extracting.

**Comment by skaws2003** [comment]
* Is the feature result supposed to be the same with that with sonopy as to the same audio?

No, probably this will not produce the same, since there are some parameters like appendEnergy, preemph that are not in sonopy. But you may try changing those parameters to make them same. I suggest setting appendEnergy=False and preemph=0.

* Or ,I needn't require the same as long as it is one correct feature extracting.

My implementation is from another MFCC implementation(which is not pytorch, though), and I have verified the result being the same. Error scale is about e-5 for each elements.

**Comment by htZhang25** [comment]
Hello， Could you tell me which (another )MFCC implementation are refered to.Thank you very much.

**Comment by skaws2003** [comment]
Check this out:
https://github.com/jameslyons/python_speech_features
